"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-13 22:11:37.932244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgcrypto provides gen_random_uuid(), used as the server default for every
    # uuid primary key below. Must be enabled before those tables are created.
    op.execute("create extension if not exists pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppressions',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_suppressions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('send_hour', sa.Integer(), server_default=sa.text('8'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('send_hour between 0 and 23', name=op.f('ck_users_send_hour_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_month', sa.Integer(), nullable=False),
    sa.Column('event_day', sa.Integer(), nullable=False),
    sa.Column('event_year', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('recipient_email', sa.Text(), nullable=True),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('event_day between 1 and 31', name=op.f('ck_events_event_day_range')),
    sa.CheckConstraint('event_month between 1 and 12', name=op.f('ck_events_event_month_range')),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_events_template_id_templates')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('events_month_day_idx', 'events', ['event_month', 'event_day'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_index('events_user_id_idx', 'events', ['user_id'], unique=False)
    op.create_table('event_reminders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.CheckConstraint('days_before between 0 and 365', name=op.f('ck_event_reminders_days_before_range')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_reminders_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_reminders')),
    sa.UniqueConstraint('event_id', 'days_before', name='event_id_days_before')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('resend_id', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notification_log_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_log')),
    sa.UniqueConstraint('event_id', 'days_before', 'occurrence_date', name='event_id_days_before_occurrence_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_log')
    op.drop_table('event_reminders')
    op.drop_index('events_user_id_idx', table_name='events')
    op.drop_index('events_month_day_idx', table_name='events', postgresql_where=sa.text('is_active'))
    op.drop_table('events')
    op.drop_table('templates')
    op.drop_table('users')
    op.drop_table('suppressions')
    # ### end Alembic commands ###
    op.execute("drop extension if exists pgcrypto")
